// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfibzxBlB_pzwOCk291mfb1E3X3iO_9SQ',
    appId: '1:137301333148:android:91a7be433f88c86f2b4959',
    messagingSenderId: '137301333148',
    projectId: 'swiva-257eb',
    storageBucket: 'swiva-257eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0n2YxYtNXhwtrY7CUpXtp8RD6eT8_g4',
    appId: '1:137301333148:ios:85699f9bffec506b2b4959',
    messagingSenderId: '137301333148',
    projectId: 'swiva-257eb',
    storageBucket: 'swiva-257eb.firebasestorage.app',
    androidClientId: '137301333148-3mlcmbn1evlhsr5qb2hi2o86qu9k6emo.apps.googleusercontent.com',
    iosClientId: '137301333148-1usgarkulk4cov7ou1aj4v80ka01uccl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehealth',
  );
}
